---
- name: Include Debian/Ubuntu installation tasks
  include_tasks: install_debian.yml
  when: ansible_os_family == "Debian"

- name: Include RedHat/Amazon Linux installation tasks
  include_tasks: install_redhat.yml
  when: ansible_os_family == "RedHat"

- name: Include configuration tasks
  include_tasks: configure.yml
